// <auto-generated />
using IT3047C_FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3047C_FinalProject.Migrations
{
    [DbContext(typeof(HikingContext))]
    [Migration("20251201105859_AddRecommendations")]
    partial class AddRecommendations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3047C_FinalProject.Models.Gear", b =>
                {
                    b.Property<int>("GearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GearId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("GearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecommendedQuantity")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("GearId");

                    b.ToTable("Gears");

                    b.HasData(
                        new
                        {
                            GearId = 1,
                            Cost = 100.0,
                            GearName = "Backpack",
                            RecommendedQuantity = 1,
                            Weight = 0.40000000000000002
                        },
                        new
                        {
                            GearId = 2,
                            Cost = 150.0,
                            GearName = "Hiking Shoes",
                            RecommendedQuantity = 1,
                            Weight = 0.5
                        },
                        new
                        {
                            GearId = 3,
                            Cost = 100.0,
                            GearName = "Trekking Poles",
                            RecommendedQuantity = 2,
                            Weight = 0.5
                        },
                        new
                        {
                            GearId = 4,
                            Cost = 50.0,
                            GearName = "2l Water Bottle",
                            RecommendedQuantity = 1,
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            GearId = 5,
                            Cost = 30.0,
                            GearName = "Hat",
                            RecommendedQuantity = 1,
                            Weight = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.HasKey("RecommendationId");

                    b.HasIndex("TrailId")
                        .IsUnique();

                    b.ToTable("Recommendations");

                    b.HasData(
                        new
                        {
                            RecommendationId = 1,
                            TrailId = 4
                        });
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.RecommendationItem", b =>
                {
                    b.Property<int>("RecommendationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationItemId"));

                    b.Property<int>("GearId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.HasKey("RecommendationItemId");

                    b.HasIndex("GearId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("RecommendationItems");

                    b.HasData(
                        new
                        {
                            RecommendationItemId = 1,
                            GearId = 1,
                            Quantity = 1,
                            RecommendationId = 1
                        },
                        new
                        {
                            RecommendationItemId = 2,
                            GearId = 2,
                            Quantity = 1,
                            RecommendationId = 1
                        },
                        new
                        {
                            RecommendationItemId = 3,
                            GearId = 4,
                            Quantity = 1,
                            RecommendationId = 1
                        });
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrailId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Park")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrailId");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            Description = "The Colerain trail is an excellent beginner level trail in the beautiful Mt. Airy Forest, located on the west side of Cincinnati. As the trail is under a mile, expect an easy forest walk that can be completed in under an hour.",
                            DifficultyLevel = 1,
                            Park = "Mt. Airy Forest",
                            State = "Ohio",
                            TrailName = "Colerain Trail"
                        },
                        new
                        {
                            TrailId = 2,
                            Description = "The Ponderosa trail is an intermediate level 4 mile hiking trail in the scenic Mt. Airy Forest. This trail will take you on a meandering path through a majority of the eastern half of the forest, and runs in tandem with multiple other trails located within the forest. If you are looking for a solid challenge, this may be the trail for you.",
                            DifficultyLevel = 3,
                            Park = "Mt. Airy Forest",
                            State = "Ohio",
                            TrailName = "Ponderosa Trail"
                        },
                        new
                        {
                            TrailId = 3,
                            Description = "Buttercup Valley and Parker Woods are a smaller nature reserve located on the west side of Cincinnati. The 1.4 mile long B Loop Trail takes you through both of the reserves, and acts as a more casual nature trail. Even so, there are still plenty of scenic twists, turns, bridges, and hills to keep the trail interesting even for more experienced hikers.",
                            DifficultyLevel = 2,
                            Park = "Buttercup Valley and Parker Woods",
                            State = "Ohio",
                            TrailName = "B Loop Trail"
                        },
                        new
                        {
                            TrailId = 4,
                            Description = "In the gorgeous Miami Whitewater Forest located in Harrison OH, hikers are treated to multiple options for trails. The main trail is the Shaker Trace Loop, which gives hikers an option between the easier 1.4 mile inner loop, or the more challenging 7.8 mile outer loop. With either choice, you will be treated to the beautiful forest, challenging inclines, refreshing waterways all on a paved pathway. If you are looking for an excellent entry level intermediate level course that’s still easy on the knees, This trail may be for you.",
                            DifficultyLevel = 4,
                            Park = "Miami Whitewater Forest",
                            State = "Ohio",
                            TrailName = "Shaker Trace Outer Loop"
                        });
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.Recommendation", b =>
                {
                    b.HasOne("IT3047C_FinalProject.Models.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.RecommendationItem", b =>
                {
                    b.HasOne("IT3047C_FinalProject.Models.Gear", "Gear")
                        .WithMany()
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IT3047C_FinalProject.Models.Recommendation", "Recommendation")
                        .WithMany("Items")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.Recommendation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
