// <auto-generated />
using IT3047C_FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3047C_FinalProject.Migrations
{
    [DbContext(typeof(HikingContext))]
    [Migration("20251101014100_GearInitialItems")]
    partial class GearInitialItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3047C_FinalProject.Models.Gear", b =>
                {
                    b.Property<int>("GearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GearId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("GearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecommendedQuantity")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("GearId");

                    b.ToTable("Gears");

                    b.HasData(
                        new
                        {
                            GearId = 1,
                            Cost = 100.0,
                            GearName = "Backpack",
                            RecommendedQuantity = 1,
                            Weight = 0.40000000000000002
                        },
                        new
                        {
                            GearId = 2,
                            Cost = 150.0,
                            GearName = "Hiking Shoes",
                            RecommendedQuantity = 1,
                            Weight = 0.5
                        },
                        new
                        {
                            GearId = 3,
                            Cost = 100.0,
                            GearName = "Trekking Poles",
                            RecommendedQuantity = 2,
                            Weight = 0.5
                        },
                        new
                        {
                            GearId = 4,
                            Cost = 50.0,
                            GearName = "2l Water Bottle",
                            RecommendedQuantity = 1,
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            GearId = 5,
                            Cost = 30.0,
                            GearName = "Hat",
                            RecommendedQuantity = 1,
                            Weight = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("IT3047C_FinalProject.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrailId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Park")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrailId");

                    b.ToTable("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
